server:
  port: 8021
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 111111
    virtual-host: RootHost
#  amqp:
#    deserialization:
#      trust:
#        all: true
